apiVersion: v1
kind: Service
metadata:
  labels:
    app: cnn-app
  name: cnn-app
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: cnn-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
