apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-app
  name: frontend-app
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30364
    port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    app: frontend-app
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
