apiVersion: v1
kind: Service
metadata:
  labels:
    app: speech-app-azure
  name: speech-app-azure
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 5005
    protocol: TCP
    targetPort: 5005
  selector:
    app: speech-app-azure
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
