apiVersion: v1
kind: Service
metadata:
  labels:
    app: speech-app-aws
  name: speech-app-aws
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 5004
    protocol: TCP
    targetPort: 5004
  selector:
    app: speech-app-aws
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
